on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  generate_docs:
    runs-on: ubuntu-20.04
    steps:
      - uses: coursier/cache-action@v6
      - uses: VirtusLab/scala-cli-setup@v0.1.7
      - uses: actions/checkout@v3
      - name: Generate SIP documentation
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: scala-cli .github/scripts/generate-docs.scala
